### ISSUE TITLE
Wireframes interativos

### ISSUE THREAD

**Issue by kaiqueRoc** [ICEI-PUC-Minas-PMV-ADS/pmv-ads-2022-1-e2-proj-int-t5-Simple_Sign#21]

**Comment by lu-rib** [comment]
![1](https://user-images.githubusercontent.com/82836965/161853514-b130bb66-b06e-4d3e-9b7b-115f8ae000d4.png)

**Comment by lu-rib** [comment]
[Suitable Pricing (3).pdf](https://github.com/ICEI-PUC-Minas-PMV-ADS/pmv-ads-2022-1-e2-proj-int-t5-Simple_Sign/files/8427649/Suitable.Pricing.3.pdf)

**Comment by lu-rib** [comment]
[WireFrame_interativo.pdf](https://github.com/ICEI-PUC-Minas-PMV-ADS/pmv-ads-2022-1-e2-proj-int-t5-Simple_Sign/files/8427663/WireFrame_interativo.pdf)

**Comment by lu-rib** [comment]
![wireframe](https://user-images.githubusercontent.com/82836965/162008176-ba7bc899-4993-47df-ba3c-6b3e51c14cb1.png)
