### ISSUE TITLE
Plano de Testes de Usabilidade

### ISSUE THREAD

**Issue by kaiqueRoc** [ICEI-PUC-Minas-PMV-ADS/pmv-ads-2022-1-e2-proj-int-t5-Simple_Sign#23]

**Comment by NaiaraHF** [comment]
[Teste de usabilidade.zip](https://github.com/ICEI-PUC-Minas-PMV-ADS/pmv-ads-2022-1-e2-proj-int-t5-Simple_Sign/files/8459054/Teste.de.usabilidade.zip)
