### ISSUE TITLE
Teste de Usabilidade

### ISSUE THREAD

**Issue by NaiaraHF** [ICEI-PUC-Minas-PMV-ADS/pmv-ads-2022-1-e2-proj-int-t5-Simple_Sign#26]
[Teste de usabilidade.zip](https://github.com/ICEI-PUC-Minas-PMV-ADS/pmv-ads-2022-1-e2-proj-int-t5-Simple_Sign/files/8459469/Teste.de.usabilidade.zip)

**Comment by lu-rib** [comment]
![Caso de Uso UML - Simple Sign](https://user-images.githubusercontent.com/82836965/162630744-3de171d2-f4eb-4f87-a991-cbd0a33d5994.png)
